/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.forteplatforms.sdk;

import com.forteplatforms.sdk.invoker.ApiClient;
import com.forteplatforms.sdk.invoker.ApiException;
import com.forteplatforms.sdk.invoker.ApiResponse;
import com.forteplatforms.sdk.invoker.Configuration;
import com.forteplatforms.sdk.invoker.Pair;

import com.forteplatforms.sdk.model.AddContactMethodRequest;
import com.forteplatforms.sdk.model.ContactMethod;
import com.forteplatforms.sdk.model.LoginUserResponse;
import com.forteplatforms.sdk.model.RegisterUserRequest;
import com.forteplatforms.sdk.model.RenewSessionTokenResponse;
import com.forteplatforms.sdk.model.UserObject;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-18T15:44:04.305503900-07:00[America/Los_Angeles]", comments = "Generator version: 7.18.0")
public class UsersServerApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public UsersServerApi() {
    this(Configuration.getDefaultApiClient());
  }

  public UsersServerApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param addContactMethodRequest  (required)
   * @return ContactMethod
   * @throws ApiException if fails to make API call
   */
  public ContactMethod createContactMethod(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull AddContactMethodRequest addContactMethodRequest) throws ApiException {
    return createContactMethod(projectId, addContactMethodRequest, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param addContactMethodRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ContactMethod
   * @throws ApiException if fails to make API call
   */
  public ContactMethod createContactMethod(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull AddContactMethodRequest addContactMethodRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<ContactMethod> localVarResponse = createContactMethodWithHttpInfo(projectId, addContactMethodRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param addContactMethodRequest  (required)
   * @return ApiResponse&lt;ContactMethod&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactMethod> createContactMethodWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull AddContactMethodRequest addContactMethodRequest) throws ApiException {
    return createContactMethodWithHttpInfo(projectId, addContactMethodRequest, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param addContactMethodRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ContactMethod&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactMethod> createContactMethodWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull AddContactMethodRequest addContactMethodRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createContactMethodRequestBuilder(projectId, addContactMethodRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createContactMethod", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ContactMethod>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ContactMethod responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ContactMethod>() {});
        

        return new ApiResponse<ContactMethod>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createContactMethodRequestBuilder(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull AddContactMethodRequest addContactMethodRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling createContactMethod");
    }
    // verify the required parameter 'addContactMethodRequest' is set
    if (addContactMethodRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'addContactMethodRequest' when calling createContactMethod");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/{projectId}/users/me/contact-methods"
        .replace("{projectId}", ApiClient.urlEncode(projectId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(addContactMethodRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteContactMethod(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId) throws ApiException {
    deleteContactMethod(projectId, contactMethodId, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void deleteContactMethod(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, Map<String, String> headers) throws ApiException {
    deleteContactMethodWithHttpInfo(projectId, contactMethodId, headers);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteContactMethodWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId) throws ApiException {
    return deleteContactMethodWithHttpInfo(projectId, contactMethodId, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteContactMethodWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteContactMethodRequestBuilder(projectId, contactMethodId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteContactMethod", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteContactMethodRequestBuilder(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling deleteContactMethod");
    }
    // verify the required parameter 'contactMethodId' is set
    if (contactMethodId == null) {
      throw new ApiException(400, "Missing the required parameter 'contactMethodId' when calling deleteContactMethod");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/{projectId}/users/me/contact-methods/{contactMethodId}"
        .replace("{projectId}", ApiClient.urlEncode(projectId.toString()))
        .replace("{contactMethodId}", ApiClient.urlEncode(contactMethodId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @return UserObject
   * @throws ApiException if fails to make API call
   */
  public UserObject getAccount(@javax.annotation.Nonnull String projectId) throws ApiException {
    return getAccount(projectId, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param headers Optional headers to include in the request
   * @return UserObject
   * @throws ApiException if fails to make API call
   */
  public UserObject getAccount(@javax.annotation.Nonnull String projectId, Map<String, String> headers) throws ApiException {
    ApiResponse<UserObject> localVarResponse = getAccountWithHttpInfo(projectId, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @return ApiResponse&lt;UserObject&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserObject> getAccountWithHttpInfo(@javax.annotation.Nonnull String projectId) throws ApiException {
    return getAccountWithHttpInfo(projectId, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UserObject&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserObject> getAccountWithHttpInfo(@javax.annotation.Nonnull String projectId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getAccountRequestBuilder(projectId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getAccount", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UserObject>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UserObject responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UserObject>() {});
        

        return new ApiResponse<UserObject>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getAccountRequestBuilder(@javax.annotation.Nonnull String projectId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling getAccount");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/{projectId}/users/me"
        .replace("{projectId}", ApiClient.urlEncode(projectId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param gCsrfToken  (required)
   * @param gCsrfToken2  (required)
   * @param credential  (required)
   * @return LoginUserResponse
   * @throws ApiException if fails to make API call
   */
  public LoginUserResponse googleAuthLoginCallback(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String gCsrfToken, @javax.annotation.Nonnull String gCsrfToken2, @javax.annotation.Nonnull String credential) throws ApiException {
    return googleAuthLoginCallback(projectId, gCsrfToken, gCsrfToken2, credential, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param gCsrfToken  (required)
   * @param gCsrfToken2  (required)
   * @param credential  (required)
   * @param headers Optional headers to include in the request
   * @return LoginUserResponse
   * @throws ApiException if fails to make API call
   */
  public LoginUserResponse googleAuthLoginCallback(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String gCsrfToken, @javax.annotation.Nonnull String gCsrfToken2, @javax.annotation.Nonnull String credential, Map<String, String> headers) throws ApiException {
    ApiResponse<LoginUserResponse> localVarResponse = googleAuthLoginCallbackWithHttpInfo(projectId, gCsrfToken, gCsrfToken2, credential, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param gCsrfToken  (required)
   * @param gCsrfToken2  (required)
   * @param credential  (required)
   * @return ApiResponse&lt;LoginUserResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LoginUserResponse> googleAuthLoginCallbackWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String gCsrfToken, @javax.annotation.Nonnull String gCsrfToken2, @javax.annotation.Nonnull String credential) throws ApiException {
    return googleAuthLoginCallbackWithHttpInfo(projectId, gCsrfToken, gCsrfToken2, credential, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param gCsrfToken  (required)
   * @param gCsrfToken2  (required)
   * @param credential  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;LoginUserResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LoginUserResponse> googleAuthLoginCallbackWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String gCsrfToken, @javax.annotation.Nonnull String gCsrfToken2, @javax.annotation.Nonnull String credential, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = googleAuthLoginCallbackRequestBuilder(projectId, gCsrfToken, gCsrfToken2, credential, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("googleAuthLoginCallback", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<LoginUserResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        LoginUserResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<LoginUserResponse>() {});
        

        return new ApiResponse<LoginUserResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder googleAuthLoginCallbackRequestBuilder(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String gCsrfToken, @javax.annotation.Nonnull String gCsrfToken2, @javax.annotation.Nonnull String credential, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling googleAuthLoginCallback");
    }
    // verify the required parameter 'gCsrfToken' is set
    if (gCsrfToken == null) {
      throw new ApiException(400, "Missing the required parameter 'gCsrfToken' when calling googleAuthLoginCallback");
    }
    // verify the required parameter 'gCsrfToken2' is set
    if (gCsrfToken2 == null) {
      throw new ApiException(400, "Missing the required parameter 'gCsrfToken2' when calling googleAuthLoginCallback");
    }
    // verify the required parameter 'credential' is set
    if (credential == null) {
      throw new ApiException(400, "Missing the required parameter 'credential' when calling googleAuthLoginCallback");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/{projectId}/users/google-auth-callback"
        .replace("{projectId}", ApiClient.urlEncode(projectId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    List<NameValuePair> formValues = new ArrayList<>();
    if (gCsrfToken2 != null) {
        formValues.add(new BasicNameValuePair("g_csrf_token", gCsrfToken2.toString()));
    }
    if (credential != null) {
        formValues.add(new BasicNameValuePair("credential", credential.toString()));
    }
    HttpEntity entity = new UrlEncodedFormEntity(formValues, java.nio.charset.StandardCharsets.UTF_8);
    ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
    try {
        entity.writeTo(formOutputStream);
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
    byte[] formBytes = formOutputStream.toByteArray();
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes)));
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param authorization  (optional)
   * @param forteUserSessionToken  (optional)
   * @throws ApiException if fails to make API call
   */
  public void logout(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken) throws ApiException {
    logout(projectId, authorization, forteUserSessionToken, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param authorization  (optional)
   * @param forteUserSessionToken  (optional)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void logout(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken, Map<String, String> headers) throws ApiException {
    logoutWithHttpInfo(projectId, authorization, forteUserSessionToken, headers);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param authorization  (optional)
   * @param forteUserSessionToken  (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> logoutWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken) throws ApiException {
    return logoutWithHttpInfo(projectId, authorization, forteUserSessionToken, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param authorization  (optional)
   * @param forteUserSessionToken  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> logoutWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = logoutRequestBuilder(projectId, authorization, forteUserSessionToken, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("logout", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder logoutRequestBuilder(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling logout");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/{projectId}/users/logout"
        .replace("{projectId}", ApiClient.urlEncode(projectId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    if (authorization != null) {
      localVarRequestBuilder.header("Authorization", authorization.toString());
    }
    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param registerUserRequest  (required)
   * @return UserObject
   * @throws ApiException if fails to make API call
   */
  public UserObject registerUser(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull RegisterUserRequest registerUserRequest) throws ApiException {
    return registerUser(projectId, registerUserRequest, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param registerUserRequest  (required)
   * @param headers Optional headers to include in the request
   * @return UserObject
   * @throws ApiException if fails to make API call
   */
  public UserObject registerUser(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull RegisterUserRequest registerUserRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<UserObject> localVarResponse = registerUserWithHttpInfo(projectId, registerUserRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param registerUserRequest  (required)
   * @return ApiResponse&lt;UserObject&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserObject> registerUserWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull RegisterUserRequest registerUserRequest) throws ApiException {
    return registerUserWithHttpInfo(projectId, registerUserRequest, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param registerUserRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UserObject&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UserObject> registerUserWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull RegisterUserRequest registerUserRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = registerUserRequestBuilder(projectId, registerUserRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("registerUser", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UserObject>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UserObject responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UserObject>() {});
        

        return new ApiResponse<UserObject>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder registerUserRequestBuilder(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull RegisterUserRequest registerUserRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling registerUser");
    }
    // verify the required parameter 'registerUserRequest' is set
    if (registerUserRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'registerUserRequest' when calling registerUser");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/{projectId}/users/register"
        .replace("{projectId}", ApiClient.urlEncode(projectId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "*/*");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(registerUserRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param authorization  (optional)
   * @param forteUserSessionToken  (optional)
   * @param renewalDurationSeconds Duration in seconds for which the renewed session token should be valid. Defaults to 31536000 seconds (1 year). (optional, default to 31536000)
   * @return RenewSessionTokenResponse
   * @throws ApiException if fails to make API call
   */
  public RenewSessionTokenResponse renewSessionToken(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken, @javax.annotation.Nullable Long renewalDurationSeconds) throws ApiException {
    return renewSessionToken(projectId, authorization, forteUserSessionToken, renewalDurationSeconds, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param authorization  (optional)
   * @param forteUserSessionToken  (optional)
   * @param renewalDurationSeconds Duration in seconds for which the renewed session token should be valid. Defaults to 31536000 seconds (1 year). (optional, default to 31536000)
   * @param headers Optional headers to include in the request
   * @return RenewSessionTokenResponse
   * @throws ApiException if fails to make API call
   */
  public RenewSessionTokenResponse renewSessionToken(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken, @javax.annotation.Nullable Long renewalDurationSeconds, Map<String, String> headers) throws ApiException {
    ApiResponse<RenewSessionTokenResponse> localVarResponse = renewSessionTokenWithHttpInfo(projectId, authorization, forteUserSessionToken, renewalDurationSeconds, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param authorization  (optional)
   * @param forteUserSessionToken  (optional)
   * @param renewalDurationSeconds Duration in seconds for which the renewed session token should be valid. Defaults to 31536000 seconds (1 year). (optional, default to 31536000)
   * @return ApiResponse&lt;RenewSessionTokenResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<RenewSessionTokenResponse> renewSessionTokenWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken, @javax.annotation.Nullable Long renewalDurationSeconds) throws ApiException {
    return renewSessionTokenWithHttpInfo(projectId, authorization, forteUserSessionToken, renewalDurationSeconds, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param authorization  (optional)
   * @param forteUserSessionToken  (optional)
   * @param renewalDurationSeconds Duration in seconds for which the renewed session token should be valid. Defaults to 31536000 seconds (1 year). (optional, default to 31536000)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;RenewSessionTokenResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<RenewSessionTokenResponse> renewSessionTokenWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken, @javax.annotation.Nullable Long renewalDurationSeconds, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = renewSessionTokenRequestBuilder(projectId, authorization, forteUserSessionToken, renewalDurationSeconds, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("renewSessionToken", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<RenewSessionTokenResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        RenewSessionTokenResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<RenewSessionTokenResponse>() {});
        

        return new ApiResponse<RenewSessionTokenResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder renewSessionTokenRequestBuilder(@javax.annotation.Nonnull String projectId, @javax.annotation.Nullable String authorization, @javax.annotation.Nullable String forteUserSessionToken, @javax.annotation.Nullable Long renewalDurationSeconds, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling renewSessionToken");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/{projectId}/users/session-token/renew"
        .replace("{projectId}", ApiClient.urlEncode(projectId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "renewalDurationSeconds";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("renewalDurationSeconds", renewalDurationSeconds));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    if (authorization != null) {
      localVarRequestBuilder.header("Authorization", authorization.toString());
    }
    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @return ContactMethod
   * @throws ApiException if fails to make API call
   */
  public ContactMethod resendContactMethodVerificationCode(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId) throws ApiException {
    return resendContactMethodVerificationCode(projectId, contactMethodId, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @param headers Optional headers to include in the request
   * @return ContactMethod
   * @throws ApiException if fails to make API call
   */
  public ContactMethod resendContactMethodVerificationCode(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, Map<String, String> headers) throws ApiException {
    ApiResponse<ContactMethod> localVarResponse = resendContactMethodVerificationCodeWithHttpInfo(projectId, contactMethodId, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @return ApiResponse&lt;ContactMethod&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactMethod> resendContactMethodVerificationCodeWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId) throws ApiException {
    return resendContactMethodVerificationCodeWithHttpInfo(projectId, contactMethodId, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ContactMethod&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactMethod> resendContactMethodVerificationCodeWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = resendContactMethodVerificationCodeRequestBuilder(projectId, contactMethodId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("resendContactMethodVerificationCode", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ContactMethod>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ContactMethod responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ContactMethod>() {});
        

        return new ApiResponse<ContactMethod>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder resendContactMethodVerificationCodeRequestBuilder(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling resendContactMethodVerificationCode");
    }
    // verify the required parameter 'contactMethodId' is set
    if (contactMethodId == null) {
      throw new ApiException(400, "Missing the required parameter 'contactMethodId' when calling resendContactMethodVerificationCode");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/{projectId}/users/me/contact-methods/{contactMethodId}/resend-verification-code"
        .replace("{projectId}", ApiClient.urlEncode(projectId.toString()))
        .replace("{contactMethodId}", ApiClient.urlEncode(contactMethodId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @param verificationCode  (required)
   * @return ContactMethod
   * @throws ApiException if fails to make API call
   */
  public ContactMethod verifyContactMethod(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, @javax.annotation.Nonnull String verificationCode) throws ApiException {
    return verifyContactMethod(projectId, contactMethodId, verificationCode, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @param verificationCode  (required)
   * @param headers Optional headers to include in the request
   * @return ContactMethod
   * @throws ApiException if fails to make API call
   */
  public ContactMethod verifyContactMethod(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, @javax.annotation.Nonnull String verificationCode, Map<String, String> headers) throws ApiException {
    ApiResponse<ContactMethod> localVarResponse = verifyContactMethodWithHttpInfo(projectId, contactMethodId, verificationCode, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @param verificationCode  (required)
   * @return ApiResponse&lt;ContactMethod&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactMethod> verifyContactMethodWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, @javax.annotation.Nonnull String verificationCode) throws ApiException {
    return verifyContactMethodWithHttpInfo(projectId, contactMethodId, verificationCode, null);
  }

  /**
   * 
   * 
   * @param projectId  (required)
   * @param contactMethodId  (required)
   * @param verificationCode  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ContactMethod&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ContactMethod> verifyContactMethodWithHttpInfo(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, @javax.annotation.Nonnull String verificationCode, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = verifyContactMethodRequestBuilder(projectId, contactMethodId, verificationCode, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("verifyContactMethod", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ContactMethod>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ContactMethod responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ContactMethod>() {});
        

        return new ApiResponse<ContactMethod>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder verifyContactMethodRequestBuilder(@javax.annotation.Nonnull String projectId, @javax.annotation.Nonnull String contactMethodId, @javax.annotation.Nonnull String verificationCode, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'projectId' is set
    if (projectId == null) {
      throw new ApiException(400, "Missing the required parameter 'projectId' when calling verifyContactMethod");
    }
    // verify the required parameter 'contactMethodId' is set
    if (contactMethodId == null) {
      throw new ApiException(400, "Missing the required parameter 'contactMethodId' when calling verifyContactMethod");
    }
    // verify the required parameter 'verificationCode' is set
    if (verificationCode == null) {
      throw new ApiException(400, "Missing the required parameter 'verificationCode' when calling verifyContactMethod");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/{projectId}/users/me/contact-methods/{contactMethodId}/verification"
        .replace("{projectId}", ApiClient.urlEncode(projectId.toString()))
        .replace("{contactMethodId}", ApiClient.urlEncode(contactMethodId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "verificationCode";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("verificationCode", verificationCode));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "*/*");

    localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
