/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.forteplatforms.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.forteplatforms.sdk.invoker.ApiClient;
/**
 * CreateServiceRequestProxyRequest
 */
@JsonPropertyOrder({
  CreateServiceRequestProxyRequest.JSON_PROPERTY_PATH,
  CreateServiceRequestProxyRequest.JSON_PROPERTY_HTTP_METHOD,
  CreateServiceRequestProxyRequest.JSON_PROPERTY_HEADERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-18T15:44:04.305503900-07:00[America/Los_Angeles]", comments = "Generator version: 7.18.0")
public class CreateServiceRequestProxyRequest {
  public static final String JSON_PROPERTY_PATH = "path";
  @javax.annotation.Nonnull
  private String path;

  public static final String JSON_PROPERTY_HTTP_METHOD = "httpMethod";
  @javax.annotation.Nonnull
  private String httpMethod;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @javax.annotation.Nonnull
  private Map<String, String> headers = new HashMap<>();

  public CreateServiceRequestProxyRequest() { 
  }

  public CreateServiceRequestProxyRequest path(@javax.annotation.Nonnull String path) {
    this.path = path;
    return this;
  }

  /**
   * Get path
   * @return path
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPath(@javax.annotation.Nonnull String path) {
    this.path = path;
  }


  public CreateServiceRequestProxyRequest httpMethod(@javax.annotation.Nonnull String httpMethod) {
    this.httpMethod = httpMethod;
    return this;
  }

  /**
   * Get httpMethod
   * @return httpMethod
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HTTP_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getHttpMethod() {
    return httpMethod;
  }


  @JsonProperty(value = JSON_PROPERTY_HTTP_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHttpMethod(@javax.annotation.Nonnull String httpMethod) {
    this.httpMethod = httpMethod;
  }


  public CreateServiceRequestProxyRequest headers(@javax.annotation.Nonnull Map<String, String> headers) {
    this.headers = headers;
    return this;
  }

  public CreateServiceRequestProxyRequest putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

  /**
   * Get headers
   * @return headers
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, String> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHeaders(@javax.annotation.Nonnull Map<String, String> headers) {
    this.headers = headers;
  }


  /**
   * Return true if this CreateServiceRequestProxyRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateServiceRequestProxyRequest createServiceRequestProxyRequest = (CreateServiceRequestProxyRequest) o;
    return Objects.equals(this.path, createServiceRequestProxyRequest.path) &&
        Objects.equals(this.httpMethod, createServiceRequestProxyRequest.httpMethod) &&
        Objects.equals(this.headers, createServiceRequestProxyRequest.headers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(path, httpMethod, headers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateServiceRequestProxyRequest {\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    httpMethod: ").append(toIndentedString(httpMethod)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `path` to the URL query string
    if (getPath() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPath()))));
    }

    // add `httpMethod` to the URL query string
    if (getHttpMethod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%shttpMethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getHttpMethod()))));
    }

    // add `headers` to the URL query string
    if (getHeaders() != null) {
      for (String _key : getHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sheaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getHeaders().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

