/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.forteplatforms.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.forteplatforms.sdk.invoker.ApiClient;
/**
 * Detailed error information from health check detection failure
 */
@JsonPropertyOrder({
  HealthCheckDetectionError.JSON_PROPERTY_ERROR_TYPE,
  HealthCheckDetectionError.JSON_PROPERTY_ERROR_MESSAGE,
  HealthCheckDetectionError.JSON_PROPERTY_EXPOSED_PORT,
  HealthCheckDetectionError.JSON_PROPERTY_DETECTED_FRAMEWORK,
  HealthCheckDetectionError.JSON_PROPERTY_SEARCHED_PATHS,
  HealthCheckDetectionError.JSON_PROPERTY_SUGGESTIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-18T15:44:04.305503900-07:00[America/Los_Angeles]", comments = "Generator version: 7.18.0")
public class HealthCheckDetectionError {
  /**
   * Type of error that occurred
   */
  public enum ErrorTypeEnum {
    TIMEOUT(String.valueOf("TIMEOUT")),
    
    NO_EXPOSED_PORT(String.valueOf("NO_EXPOSED_PORT")),
    
    MULTIPLE_EXPOSED_PORTS(String.valueOf("MULTIPLE_EXPOSED_PORTS")),
    
    INVALID_PORT_NUMBER(String.valueOf("INVALID_PORT_NUMBER")),
    
    NO_HEALTH_CHECK_FOUND(String.valueOf("NO_HEALTH_CHECK_FOUND")),
    
    FRAMEWORK_NOT_RECOGNIZED(String.valueOf("FRAMEWORK_NOT_RECOGNIZED")),
    
    NO_HTTP_ROUTES_FOUND(String.valueOf("NO_HTTP_ROUTES_FOUND")),
    
    TCP_ONLY_SERVICE(String.valueOf("TCP_ONLY_SERVICE")),
    
    INTERNAL_ERROR(String.valueOf("INTERNAL_ERROR"));

    private String value;

    ErrorTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ErrorTypeEnum fromValue(String value) {
      for (ErrorTypeEnum b : ErrorTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ERROR_TYPE = "errorType";
  @javax.annotation.Nullable
  private ErrorTypeEnum errorType;

  public static final String JSON_PROPERTY_ERROR_MESSAGE = "errorMessage";
  @javax.annotation.Nullable
  private String errorMessage;

  public static final String JSON_PROPERTY_EXPOSED_PORT = "exposedPort";
  @javax.annotation.Nullable
  private Integer exposedPort;

  public static final String JSON_PROPERTY_DETECTED_FRAMEWORK = "detectedFramework";
  @javax.annotation.Nullable
  private String detectedFramework;

  public static final String JSON_PROPERTY_SEARCHED_PATHS = "searchedPaths";
  @javax.annotation.Nullable
  private List<String> searchedPaths = new ArrayList<>();

  public static final String JSON_PROPERTY_SUGGESTIONS = "suggestions";
  @javax.annotation.Nullable
  private List<String> suggestions = new ArrayList<>();

  public HealthCheckDetectionError() { 
  }

  public HealthCheckDetectionError errorType(@javax.annotation.Nullable ErrorTypeEnum errorType) {
    this.errorType = errorType;
    return this;
  }

  /**
   * Type of error that occurred
   * @return errorType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ErrorTypeEnum getErrorType() {
    return errorType;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorType(@javax.annotation.Nullable ErrorTypeEnum errorType) {
    this.errorType = errorType;
  }


  public HealthCheckDetectionError errorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * Detailed error message explaining what went wrong
   * @return errorMessage
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERROR_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getErrorMessage() {
    return errorMessage;
  }


  @JsonProperty(value = JSON_PROPERTY_ERROR_MESSAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }


  public HealthCheckDetectionError exposedPort(@javax.annotation.Nullable Integer exposedPort) {
    this.exposedPort = exposedPort;
    return this;
  }

  /**
   * Port number that was exposed in the Dockerfile (if detected)
   * @return exposedPort
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EXPOSED_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getExposedPort() {
    return exposedPort;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPOSED_PORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExposedPort(@javax.annotation.Nullable Integer exposedPort) {
    this.exposedPort = exposedPort;
  }


  public HealthCheckDetectionError detectedFramework(@javax.annotation.Nullable String detectedFramework) {
    this.detectedFramework = detectedFramework;
    return this;
  }

  /**
   * Application framework that was detected (if any)
   * @return detectedFramework
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DETECTED_FRAMEWORK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDetectedFramework() {
    return detectedFramework;
  }


  @JsonProperty(value = JSON_PROPERTY_DETECTED_FRAMEWORK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetectedFramework(@javax.annotation.Nullable String detectedFramework) {
    this.detectedFramework = detectedFramework;
  }


  public HealthCheckDetectionError searchedPaths(@javax.annotation.Nullable List<String> searchedPaths) {
    this.searchedPaths = searchedPaths;
    return this;
  }

  public HealthCheckDetectionError addSearchedPathsItem(String searchedPathsItem) {
    if (this.searchedPaths == null) {
      this.searchedPaths = new ArrayList<>();
    }
    this.searchedPaths.add(searchedPathsItem);
    return this;
  }

  /**
   * Health check endpoint paths that were searched
   * @return searchedPaths
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SEARCHED_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getSearchedPaths() {
    return searchedPaths;
  }


  @JsonProperty(value = JSON_PROPERTY_SEARCHED_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchedPaths(@javax.annotation.Nullable List<String> searchedPaths) {
    this.searchedPaths = searchedPaths;
  }


  public HealthCheckDetectionError suggestions(@javax.annotation.Nullable List<String> suggestions) {
    this.suggestions = suggestions;
    return this;
  }

  public HealthCheckDetectionError addSuggestionsItem(String suggestionsItem) {
    if (this.suggestions == null) {
      this.suggestions = new ArrayList<>();
    }
    this.suggestions.add(suggestionsItem);
    return this;
  }

  /**
   * Actionable suggestions for resolving the error
   * @return suggestions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUGGESTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getSuggestions() {
    return suggestions;
  }


  @JsonProperty(value = JSON_PROPERTY_SUGGESTIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuggestions(@javax.annotation.Nullable List<String> suggestions) {
    this.suggestions = suggestions;
  }


  /**
   * Return true if this HealthCheckDetectionError object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HealthCheckDetectionError healthCheckDetectionError = (HealthCheckDetectionError) o;
    return Objects.equals(this.errorType, healthCheckDetectionError.errorType) &&
        Objects.equals(this.errorMessage, healthCheckDetectionError.errorMessage) &&
        Objects.equals(this.exposedPort, healthCheckDetectionError.exposedPort) &&
        Objects.equals(this.detectedFramework, healthCheckDetectionError.detectedFramework) &&
        Objects.equals(this.searchedPaths, healthCheckDetectionError.searchedPaths) &&
        Objects.equals(this.suggestions, healthCheckDetectionError.suggestions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorType, errorMessage, exposedPort, detectedFramework, searchedPaths, suggestions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HealthCheckDetectionError {\n");
    sb.append("    errorType: ").append(toIndentedString(errorType)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    exposedPort: ").append(toIndentedString(exposedPort)).append("\n");
    sb.append("    detectedFramework: ").append(toIndentedString(detectedFramework)).append("\n");
    sb.append("    searchedPaths: ").append(toIndentedString(searchedPaths)).append("\n");
    sb.append("    suggestions: ").append(toIndentedString(suggestions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `errorType` to the URL query string
    if (getErrorType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serrorType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorType()))));
    }

    // add `errorMessage` to the URL query string
    if (getErrorMessage() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serrorMessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getErrorMessage()))));
    }

    // add `exposedPort` to the URL query string
    if (getExposedPort() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sexposedPort%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExposedPort()))));
    }

    // add `detectedFramework` to the URL query string
    if (getDetectedFramework() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdetectedFramework%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDetectedFramework()))));
    }

    // add `searchedPaths` to the URL query string
    if (getSearchedPaths() != null) {
      for (int i = 0; i < getSearchedPaths().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssearchedPaths%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getSearchedPaths().get(i)))));
      }
    }

    // add `suggestions` to the URL query string
    if (getSuggestions() != null) {
      for (int i = 0; i < getSuggestions().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssuggestions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getSuggestions().get(i)))));
      }
    }

    return joiner.toString();
  }
}

