/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.forteplatforms.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.forteplatforms.sdk.invoker.ApiClient;
/**
 * RegisterUserRequest
 */
@JsonPropertyOrder({
  RegisterUserRequest.JSON_PROPERTY_FULL_NAME,
  RegisterUserRequest.JSON_PROPERTY_EMAIL,
  RegisterUserRequest.JSON_PROPERTY_PHONE_NUMBER,
  RegisterUserRequest.JSON_PROPERTY_CUSTOM_METADATA_ATTRIBUTES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-18T15:44:04.305503900-07:00[America/Los_Angeles]", comments = "Generator version: 7.18.0")
public class RegisterUserRequest {
  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  @javax.annotation.Nullable
  private String fullName;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_PHONE_NUMBER = "phoneNumber";
  @javax.annotation.Nullable
  private String phoneNumber;

  public static final String JSON_PROPERTY_CUSTOM_METADATA_ATTRIBUTES = "customMetadataAttributes";
  @javax.annotation.Nullable
  private Map<String, Object> customMetadataAttributes = new HashMap<>();

  public RegisterUserRequest() { 
  }

  public RegisterUserRequest fullName(@javax.annotation.Nullable String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * Get fullName
   * @return fullName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFullName() {
    return fullName;
  }


  @JsonProperty(value = JSON_PROPERTY_FULL_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullName(@javax.annotation.Nullable String fullName) {
    this.fullName = fullName;
  }


  public RegisterUserRequest email(@javax.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public RegisterUserRequest phoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Get phoneNumber
   * @return phoneNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhoneNumber() {
    return phoneNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public RegisterUserRequest customMetadataAttributes(@javax.annotation.Nullable Map<String, Object> customMetadataAttributes) {
    this.customMetadataAttributes = customMetadataAttributes;
    return this;
  }

  public RegisterUserRequest putCustomMetadataAttributesItem(String key, Object customMetadataAttributesItem) {
    if (this.customMetadataAttributes == null) {
      this.customMetadataAttributes = new HashMap<>();
    }
    this.customMetadataAttributes.put(key, customMetadataAttributesItem);
    return this;
  }

  /**
   * Get customMetadataAttributes
   * @return customMetadataAttributes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_METADATA_ATTRIBUTES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getCustomMetadataAttributes() {
    return customMetadataAttributes;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_METADATA_ATTRIBUTES, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomMetadataAttributes(@javax.annotation.Nullable Map<String, Object> customMetadataAttributes) {
    this.customMetadataAttributes = customMetadataAttributes;
  }


  /**
   * Return true if this RegisterUserRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisterUserRequest registerUserRequest = (RegisterUserRequest) o;
    return Objects.equals(this.fullName, registerUserRequest.fullName) &&
        Objects.equals(this.email, registerUserRequest.email) &&
        Objects.equals(this.phoneNumber, registerUserRequest.phoneNumber) &&
        Objects.equals(this.customMetadataAttributes, registerUserRequest.customMetadataAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fullName, email, phoneNumber, customMetadataAttributes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisterUserRequest {\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    customMetadataAttributes: ").append(toIndentedString(customMetadataAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `fullName` to the URL query string
    if (getFullName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfullName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFullName()))));
    }

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `phoneNumber` to the URL query string
    if (getPhoneNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sphoneNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhoneNumber()))));
    }

    // add `customMetadataAttributes` to the URL query string
    if (getCustomMetadataAttributes() != null) {
      for (String _key : getCustomMetadataAttributes().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scustomMetadataAttributes%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getCustomMetadataAttributes().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getCustomMetadataAttributes().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

