/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.forteplatforms.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.forteplatforms.sdk.invoker.ApiClient;
/**
 * Results from analyzing the repository structure
 */
@JsonPropertyOrder({
  RepositoryAnalysis.JSON_PROPERTY_DETECTED_FRAMEWORKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-18T15:44:04.305503900-07:00[America/Los_Angeles]", comments = "Generator version: 7.18.0")
public class RepositoryAnalysis {
  public static final String JSON_PROPERTY_DETECTED_FRAMEWORKS = "detectedFrameworks";
  @javax.annotation.Nullable
  private List<String> detectedFrameworks = new ArrayList<>();

  public RepositoryAnalysis() { 
  }

  public RepositoryAnalysis detectedFrameworks(@javax.annotation.Nullable List<String> detectedFrameworks) {
    this.detectedFrameworks = detectedFrameworks;
    return this;
  }

  public RepositoryAnalysis addDetectedFrameworksItem(String detectedFrameworksItem) {
    if (this.detectedFrameworks == null) {
      this.detectedFrameworks = new ArrayList<>();
    }
    this.detectedFrameworks.add(detectedFrameworksItem);
    return this;
  }

  /**
   * Web frameworks or application frameworks detected
   * @return detectedFrameworks
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DETECTED_FRAMEWORKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getDetectedFrameworks() {
    return detectedFrameworks;
  }


  @JsonProperty(value = JSON_PROPERTY_DETECTED_FRAMEWORKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetectedFrameworks(@javax.annotation.Nullable List<String> detectedFrameworks) {
    this.detectedFrameworks = detectedFrameworks;
  }


  /**
   * Return true if this RepositoryAnalysis object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryAnalysis repositoryAnalysis = (RepositoryAnalysis) o;
    return Objects.equals(this.detectedFrameworks, repositoryAnalysis.detectedFrameworks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(detectedFrameworks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryAnalysis {\n");
    sb.append("    detectedFrameworks: ").append(toIndentedString(detectedFrameworks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `detectedFrameworks` to the URL query string
    if (getDetectedFrameworks() != null) {
      for (int i = 0; i < getDetectedFrameworks().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdetectedFrameworks%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getDetectedFrameworks().get(i)))));
      }
    }

    return joiner.toString();
  }
}

