/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.forteplatforms.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.forteplatforms.sdk.model.RequestLogObjectMeta;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.forteplatforms.sdk.invoker.ApiClient;
/**
 * RequestLogObject
 */
@JsonPropertyOrder({
  RequestLogObject.JSON_PROPERTY_REQUEST_ID,
  RequestLogObject.JSON_PROPERTY_TIMESTAMP,
  RequestLogObject.JSON_PROPERTY_SOURCE_IP_ADDRESS,
  RequestLogObject.JSON_PROPERTY_REQUEST_LOG_OBJECT_META,
  RequestLogObject.JSON_PROPERTY_TARGET_LATENCY_MILLISECONDS,
  RequestLogObject.JSON_PROPERTY_INTEGRATION_LATENCY_MILLISECONDS,
  RequestLogObject.JSON_PROPERTY_TOTAL_LATENCY_MILLISECONDS,
  RequestLogObject.JSON_PROPERTY_REQUEST_BODY,
  RequestLogObject.JSON_PROPERTY_RESPONSE_BODY,
  RequestLogObject.JSON_PROPERTY_STATUS_CODE,
  RequestLogObject.JSON_PROPERTY_REQUEST_HEADERS,
  RequestLogObject.JSON_PROPERTY_RESPONSE_HEADERS,
  RequestLogObject.JSON_PROPERTY_RETRY_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-18T15:44:04.305503900-07:00[America/Los_Angeles]", comments = "Generator version: 7.18.0")
public class RequestLogObject {
  public static final String JSON_PROPERTY_REQUEST_ID = "requestId";
  @javax.annotation.Nullable
  private String requestId;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nonnull
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_SOURCE_IP_ADDRESS = "sourceIpAddress";
  @javax.annotation.Nullable
  private String sourceIpAddress;

  public static final String JSON_PROPERTY_REQUEST_LOG_OBJECT_META = "requestLogObjectMeta";
  @javax.annotation.Nonnull
  private RequestLogObjectMeta requestLogObjectMeta;

  public static final String JSON_PROPERTY_TARGET_LATENCY_MILLISECONDS = "targetLatencyMilliseconds";
  @javax.annotation.Nonnull
  private Long targetLatencyMilliseconds;

  public static final String JSON_PROPERTY_INTEGRATION_LATENCY_MILLISECONDS = "integrationLatencyMilliseconds";
  @javax.annotation.Nonnull
  private Long integrationLatencyMilliseconds;

  public static final String JSON_PROPERTY_TOTAL_LATENCY_MILLISECONDS = "totalLatencyMilliseconds";
  @javax.annotation.Nonnull
  private Long totalLatencyMilliseconds;

  public static final String JSON_PROPERTY_REQUEST_BODY = "requestBody";
  @javax.annotation.Nullable
  private String requestBody;

  public static final String JSON_PROPERTY_RESPONSE_BODY = "responseBody";
  @javax.annotation.Nullable
  private String responseBody;

  public static final String JSON_PROPERTY_STATUS_CODE = "statusCode";
  @javax.annotation.Nonnull
  private Integer statusCode;

  public static final String JSON_PROPERTY_REQUEST_HEADERS = "requestHeaders";
  @javax.annotation.Nonnull
  private Map<String, String> requestHeaders = new HashMap<>();

  public static final String JSON_PROPERTY_RESPONSE_HEADERS = "responseHeaders";
  @javax.annotation.Nonnull
  private Map<String, String> responseHeaders = new HashMap<>();

  public static final String JSON_PROPERTY_RETRY_COUNT = "retryCount";
  @javax.annotation.Nullable
  private Integer retryCount;

  public RequestLogObject() { 
  }

  public RequestLogObject requestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
    return this;
  }

  /**
   * Get requestId
   * @return requestId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRequestId() {
    return requestId;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestId(@javax.annotation.Nullable String requestId) {
    this.requestId = requestId;
  }


  public RequestLogObject timestamp(@javax.annotation.Nonnull OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(value = JSON_PROPERTY_TIMESTAMP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimestamp(@javax.annotation.Nonnull OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public RequestLogObject sourceIpAddress(@javax.annotation.Nullable String sourceIpAddress) {
    this.sourceIpAddress = sourceIpAddress;
    return this;
  }

  /**
   * Get sourceIpAddress
   * @return sourceIpAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SOURCE_IP_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSourceIpAddress() {
    return sourceIpAddress;
  }


  @JsonProperty(value = JSON_PROPERTY_SOURCE_IP_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceIpAddress(@javax.annotation.Nullable String sourceIpAddress) {
    this.sourceIpAddress = sourceIpAddress;
  }


  public RequestLogObject requestLogObjectMeta(@javax.annotation.Nonnull RequestLogObjectMeta requestLogObjectMeta) {
    this.requestLogObjectMeta = requestLogObjectMeta;
    return this;
  }

  /**
   * Get requestLogObjectMeta
   * @return requestLogObjectMeta
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUEST_LOG_OBJECT_META, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RequestLogObjectMeta getRequestLogObjectMeta() {
    return requestLogObjectMeta;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_LOG_OBJECT_META, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestLogObjectMeta(@javax.annotation.Nonnull RequestLogObjectMeta requestLogObjectMeta) {
    this.requestLogObjectMeta = requestLogObjectMeta;
  }


  public RequestLogObject targetLatencyMilliseconds(@javax.annotation.Nonnull Long targetLatencyMilliseconds) {
    this.targetLatencyMilliseconds = targetLatencyMilliseconds;
    return this;
  }

  /**
   * Get targetLatencyMilliseconds
   * @return targetLatencyMilliseconds
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TARGET_LATENCY_MILLISECONDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getTargetLatencyMilliseconds() {
    return targetLatencyMilliseconds;
  }


  @JsonProperty(value = JSON_PROPERTY_TARGET_LATENCY_MILLISECONDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTargetLatencyMilliseconds(@javax.annotation.Nonnull Long targetLatencyMilliseconds) {
    this.targetLatencyMilliseconds = targetLatencyMilliseconds;
  }


  public RequestLogObject integrationLatencyMilliseconds(@javax.annotation.Nonnull Long integrationLatencyMilliseconds) {
    this.integrationLatencyMilliseconds = integrationLatencyMilliseconds;
    return this;
  }

  /**
   * Get integrationLatencyMilliseconds
   * @return integrationLatencyMilliseconds
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INTEGRATION_LATENCY_MILLISECONDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getIntegrationLatencyMilliseconds() {
    return integrationLatencyMilliseconds;
  }


  @JsonProperty(value = JSON_PROPERTY_INTEGRATION_LATENCY_MILLISECONDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIntegrationLatencyMilliseconds(@javax.annotation.Nonnull Long integrationLatencyMilliseconds) {
    this.integrationLatencyMilliseconds = integrationLatencyMilliseconds;
  }


  public RequestLogObject totalLatencyMilliseconds(@javax.annotation.Nonnull Long totalLatencyMilliseconds) {
    this.totalLatencyMilliseconds = totalLatencyMilliseconds;
    return this;
  }

  /**
   * Get totalLatencyMilliseconds
   * @return totalLatencyMilliseconds
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL_LATENCY_MILLISECONDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getTotalLatencyMilliseconds() {
    return totalLatencyMilliseconds;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_LATENCY_MILLISECONDS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalLatencyMilliseconds(@javax.annotation.Nonnull Long totalLatencyMilliseconds) {
    this.totalLatencyMilliseconds = totalLatencyMilliseconds;
  }


  public RequestLogObject requestBody(@javax.annotation.Nullable String requestBody) {
    this.requestBody = requestBody;
    return this;
  }

  /**
   * Get requestBody
   * @return requestBody
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REQUEST_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRequestBody() {
    return requestBody;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestBody(@javax.annotation.Nullable String requestBody) {
    this.requestBody = requestBody;
  }


  public RequestLogObject responseBody(@javax.annotation.Nullable String responseBody) {
    this.responseBody = responseBody;
    return this;
  }

  /**
   * Get responseBody
   * @return responseBody
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPONSE_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getResponseBody() {
    return responseBody;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponseBody(@javax.annotation.Nullable String responseBody) {
    this.responseBody = responseBody;
  }


  public RequestLogObject statusCode(@javax.annotation.Nonnull Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * Get statusCode
   * @return statusCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getStatusCode() {
    return statusCode;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatusCode(@javax.annotation.Nonnull Integer statusCode) {
    this.statusCode = statusCode;
  }


  public RequestLogObject requestHeaders(@javax.annotation.Nonnull Map<String, String> requestHeaders) {
    this.requestHeaders = requestHeaders;
    return this;
  }

  public RequestLogObject putRequestHeadersItem(String key, String requestHeadersItem) {
    if (this.requestHeaders == null) {
      this.requestHeaders = new HashMap<>();
    }
    this.requestHeaders.put(key, requestHeadersItem);
    return this;
  }

  /**
   * Get requestHeaders
   * @return requestHeaders
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REQUEST_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, String> getRequestHeaders() {
    return requestHeaders;
  }


  @JsonProperty(value = JSON_PROPERTY_REQUEST_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRequestHeaders(@javax.annotation.Nonnull Map<String, String> requestHeaders) {
    this.requestHeaders = requestHeaders;
  }


  public RequestLogObject responseHeaders(@javax.annotation.Nonnull Map<String, String> responseHeaders) {
    this.responseHeaders = responseHeaders;
    return this;
  }

  public RequestLogObject putResponseHeadersItem(String key, String responseHeadersItem) {
    if (this.responseHeaders == null) {
      this.responseHeaders = new HashMap<>();
    }
    this.responseHeaders.put(key, responseHeadersItem);
    return this;
  }

  /**
   * Get responseHeaders
   * @return responseHeaders
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESPONSE_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, String> getResponseHeaders() {
    return responseHeaders;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE_HEADERS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseHeaders(@javax.annotation.Nonnull Map<String, String> responseHeaders) {
    this.responseHeaders = responseHeaders;
  }


  public RequestLogObject retryCount(@javax.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
    return this;
  }

  /**
   * Get retryCount
   * @return retryCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETRY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getRetryCount() {
    return retryCount;
  }


  @JsonProperty(value = JSON_PROPERTY_RETRY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetryCount(@javax.annotation.Nullable Integer retryCount) {
    this.retryCount = retryCount;
  }


  /**
   * Return true if this RequestLogObject object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestLogObject requestLogObject = (RequestLogObject) o;
    return Objects.equals(this.requestId, requestLogObject.requestId) &&
        Objects.equals(this.timestamp, requestLogObject.timestamp) &&
        Objects.equals(this.sourceIpAddress, requestLogObject.sourceIpAddress) &&
        Objects.equals(this.requestLogObjectMeta, requestLogObject.requestLogObjectMeta) &&
        Objects.equals(this.targetLatencyMilliseconds, requestLogObject.targetLatencyMilliseconds) &&
        Objects.equals(this.integrationLatencyMilliseconds, requestLogObject.integrationLatencyMilliseconds) &&
        Objects.equals(this.totalLatencyMilliseconds, requestLogObject.totalLatencyMilliseconds) &&
        Objects.equals(this.requestBody, requestLogObject.requestBody) &&
        Objects.equals(this.responseBody, requestLogObject.responseBody) &&
        Objects.equals(this.statusCode, requestLogObject.statusCode) &&
        Objects.equals(this.requestHeaders, requestLogObject.requestHeaders) &&
        Objects.equals(this.responseHeaders, requestLogObject.responseHeaders) &&
        Objects.equals(this.retryCount, requestLogObject.retryCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestId, timestamp, sourceIpAddress, requestLogObjectMeta, targetLatencyMilliseconds, integrationLatencyMilliseconds, totalLatencyMilliseconds, requestBody, responseBody, statusCode, requestHeaders, responseHeaders, retryCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestLogObject {\n");
    sb.append("    requestId: ").append(toIndentedString(requestId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    sourceIpAddress: ").append(toIndentedString(sourceIpAddress)).append("\n");
    sb.append("    requestLogObjectMeta: ").append(toIndentedString(requestLogObjectMeta)).append("\n");
    sb.append("    targetLatencyMilliseconds: ").append(toIndentedString(targetLatencyMilliseconds)).append("\n");
    sb.append("    integrationLatencyMilliseconds: ").append(toIndentedString(integrationLatencyMilliseconds)).append("\n");
    sb.append("    totalLatencyMilliseconds: ").append(toIndentedString(totalLatencyMilliseconds)).append("\n");
    sb.append("    requestBody: ").append(toIndentedString(requestBody)).append("\n");
    sb.append("    responseBody: ").append(toIndentedString(responseBody)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    requestHeaders: ").append(toIndentedString(requestHeaders)).append("\n");
    sb.append("    responseHeaders: ").append(toIndentedString(responseHeaders)).append("\n");
    sb.append("    retryCount: ").append(toIndentedString(retryCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `requestId` to the URL query string
    if (getRequestId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequestId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestId()))));
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stimestamp%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTimestamp()))));
    }

    // add `sourceIpAddress` to the URL query string
    if (getSourceIpAddress() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssourceIpAddress%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSourceIpAddress()))));
    }

    // add `requestLogObjectMeta` to the URL query string
    if (getRequestLogObjectMeta() != null) {
      joiner.add(getRequestLogObjectMeta().toUrlQueryString(prefix + "requestLogObjectMeta" + suffix));
    }

    // add `targetLatencyMilliseconds` to the URL query string
    if (getTargetLatencyMilliseconds() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stargetLatencyMilliseconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetLatencyMilliseconds()))));
    }

    // add `integrationLatencyMilliseconds` to the URL query string
    if (getIntegrationLatencyMilliseconds() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sintegrationLatencyMilliseconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIntegrationLatencyMilliseconds()))));
    }

    // add `totalLatencyMilliseconds` to the URL query string
    if (getTotalLatencyMilliseconds() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotalLatencyMilliseconds%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalLatencyMilliseconds()))));
    }

    // add `requestBody` to the URL query string
    if (getRequestBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srequestBody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRequestBody()))));
    }

    // add `responseBody` to the URL query string
    if (getResponseBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sresponseBody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResponseBody()))));
    }

    // add `statusCode` to the URL query string
    if (getStatusCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatusCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusCode()))));
    }

    // add `requestHeaders` to the URL query string
    if (getRequestHeaders() != null) {
      for (String _key : getRequestHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%srequestHeaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getRequestHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getRequestHeaders().get(_key)))));
      }
    }

    // add `responseHeaders` to the URL query string
    if (getResponseHeaders() != null) {
      for (String _key : getResponseHeaders().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sresponseHeaders%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getResponseHeaders().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getResponseHeaders().get(_key)))));
      }
    }

    // add `retryCount` to the URL query string
    if (getRetryCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sretryCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRetryCount()))));
    }

    return joiner.toString();
  }
}

